var LOCAL_DICT = {
  "abandon": {
    word: "abandon", phonetic: "/əˈbændən/", pos: "v.",
    translation: "放弃，抛弃", level: "CET-4",
    roots: [
      { part: "a-", meaning: "不/无" },
      { part: "band", meaning: "绑住" },
      { part: "-on", meaning: "动词后缀" }
    ],
    memory: "a(不)+band(绑住)→不再绑住→放弃",
    example: { en: "Never abandon your dreams.", cn: "永远不要放弃你的梦想。" }
  },
  "ability": {
    word: "ability", phonetic: "/əˈbɪləti/", pos: "n.",
    translation: "能力，才能", level: "CET-4",
    roots: [
      { part: "abil", meaning: "能够" },
      { part: "-ity", meaning: "名词后缀" }
    ],
    memory: "abil(能够)+ity(名词)→能够做某事→能力",
    example: { en: "She has the ability to solve problems quickly.", cn: "她有快速解决问题的能力。" }
  },
  "able": { word: "able", phonetic: "/ˈeɪbl/", pos: "adj.", translation: "能够的，有能力的", level: "CET-4", example: { en: "He is able to speak English.", cn: "他能说英语。" } },
  "about": { word: "about", phonetic: "/əˈbaʊt/", pos: "prep.", translation: "关于，大约", level: "CET-4", example: { en: "What is the book about?", cn: "这本书是关于什么的？" } },
  "above": { word: "above", phonetic: "/əˈbʌv/", pos: "prep./adv.", translation: "在...上面", level: "CET-4", example: { en: "The birds flew above the clouds.", cn: "鸟儿在云层上方飞过。" } },
  "abroad": { word: "abroad", phonetic: "/əˈbrɔːd/", pos: "adv.", translation: "在国外，到国外", level: "CET-4", example: { en: "She wants to study abroad.", cn: "她想出国留学。" } },
  "absence": { word: "absence", phonetic: "/ˈæbsəns/", pos: "n.", translation: "缺席，不在", level: "CET-4", example: { en: "His absence was noticed by everyone.", cn: "大家都注意到了他的缺席。" } },
  "absolute": { word: "absolute", phonetic: "/ˈæbsəluːt/", pos: "adj.", translation: "绝对的，完全的", level: "CET-4", example: { en: "I have absolute confidence in you.", cn: "我对你有绝对的信心。" } },
  "absorb": { word: "absorb", phonetic: "/əbˈzɔːrb/", pos: "v.", translation: "吸收，吸引", level: "CET-4", example: { en: "Plants absorb sunlight.", cn: "植物吸收阳光。" } },
  "accept": { word: "accept", phonetic: "/əkˈsept/", pos: "v.", translation: "接受，承认", level: "CET-4", example: { en: "I accept your invitation.", cn: "我接受你的邀请。" } },
  "access": { word: "access", phonetic: "/ˈækses/", pos: "n./v.", translation: "通道，进入；访问", level: "CET-4", example: { en: "You need a password to access the system.", cn: "你需要密码才能访问系统。" } },
  "accident": { word: "accident", phonetic: "/ˈæksɪdənt/", pos: "n.", translation: "事故，意外", level: "CET-4", example: { en: "The accident happened on the highway.", cn: "事故发生在高速公路上。" } },
  "accomplish": { word: "accomplish", phonetic: "/əˈkɑːmplɪʃ/", pos: "v.", translation: "完成，实现", level: "CET-4", example: { en: "We accomplished our goal.", cn: "我们完成了目标。" } },
  "according": { word: "according", phonetic: "/əˈkɔːrdɪŋ/", pos: "prep.", translation: "根据，按照", level: "CET-4", example: { en: "According to the weather report, it will rain.", cn: "根据天气预报，将会下雨。" } },
  "account": { word: "account", phonetic: "/əˈkaʊnt/", pos: "n./v.", translation: "账户；解释", level: "CET-4", example: { en: "I opened a bank account.", cn: "我开了一个银行账户。" } },
  "achieve": { word: "achieve", phonetic: "/əˈtʃiːv/", pos: "v.", translation: "达到，实现", level: "CET-4", example: { en: "Work hard to achieve your dreams.", cn: "努力实现你的梦想。" } },
  "acknowledge": { word: "acknowledge", phonetic: "/əkˈnɑːlɪdʒ/", pos: "v.", translation: "承认，确认", level: "CET-4", example: { en: "He acknowledged his mistake.", cn: "他承认了自己的错误。" } },
  "acquire": { word: "acquire", phonetic: "/əˈkwaɪər/", pos: "v.", translation: "获得，习得", level: "CET-4", example: { en: "It takes time to acquire a new skill.", cn: "掌握新技能需要时间。" } },
  "across": { word: "across", phonetic: "/əˈkrɔːs/", pos: "prep./adv.", translation: "穿过，横过", level: "CET-4", example: { en: "The bridge stretches across the river.", cn: "桥横跨在河上。" } },
  "act": { word: "act", phonetic: "/ækt/", pos: "v./n.", translation: "行动；表演", level: "CET-4", example: { en: "We need to act quickly.", cn: "我们需要快速行动。" } },
  "action": { word: "action", phonetic: "/ˈækʃn/", pos: "n.", translation: "行动，动作", level: "CET-4", example: { en: "Actions speak louder than words.", cn: "行动胜于言语。" } },
  "active": { word: "active", phonetic: "/ˈæktɪv/", pos: "adj.", translation: "积极的，主动的", level: "CET-4", example: { en: "She is an active member of the club.", cn: "她是俱乐部的活跃成员。" } },
  "activity": { word: "activity", phonetic: "/ækˈtɪvəti/", pos: "n.", translation: "活动", level: "CET-4", example: { en: "Outdoor activities are good for health.", cn: "户外活动对健康有益。" } },
  "actor": { word: "actor", phonetic: "/ˈæktər/", pos: "n.", translation: "演员", level: "CET-4", example: { en: "He is a famous actor.", cn: "他是一位著名演员。" } },
  "actress": { word: "actress", phonetic: "/ˈæktrəs/", pos: "n.", translation: "女演员", level: "CET-4", example: { en: "She is a beautiful actress.", cn: "她是一位美丽的女演员。" } },
  "actual": { word: "actual", phonetic: "/ˈæktʃuəl/", pos: "adj.", translation: "实际的，真实的", level: "CET-4", example: { en: "What is the actual situation?", cn: "实际情况是什么？" } },
  "adapt": { word: "adapt", phonetic: "/əˈdæpt/", pos: "v.", translation: "适应，改编", level: "CET-4", example: { en: "You need to adapt to the new environment.", cn: "你需要适应新环境。" } },
  "add": { word: "add", phonetic: "/æd/", pos: "v.", translation: "添加，增加", level: "CET-4", example: { en: "Please add some sugar to the coffee.", cn: "请往咖啡里加些糖。" } },
  "address": { word: "address", phonetic: "/əˈdres/", pos: "n./v.", translation: "地址；发表演讲", level: "CET-4", example: { en: "What is your email address?", cn: "你的电子邮件地址是什么？" } },
  "adequate": { word: "adequate", phonetic: "/ˈædɪkwət/", pos: "adj.", translation: "足够的，适当的", level: "CET-4", example: { en: "The supply is adequate for our needs.", cn: "供应足以满足我们的需求。" } },
  "adjust": { word: "adjust", phonetic: "/əˈdʒʌst/", pos: "v.", translation: "调整，适应", level: "CET-4", example: { en: "Please adjust the volume.", cn: "请调整音量。" } },
  "admire": { word: "admire", phonetic: "/ədˈmaɪər/", pos: "v.", translation: "钦佩，赞赏", level: "CET-4", example: { en: "I admire her courage.", cn: "我钦佩她的勇气。" } },
  "admit": { word: "admit", phonetic: "/ədˈmɪt/", pos: "v.", translation: "承认，允许进入", level: "CET-4", example: { en: "He admitted his mistake.", cn: "他承认了错误。" } },
  "adopt": { word: "adopt", phonetic: "/əˈdɑːpt/", pos: "v.", translation: "采纳，收养", level: "CET-4", example: { en: "We should adopt a positive attitude.", cn: "我们应该采取积极的态度。" } },
  "adult": { word: "adult", phonetic: "/ˈædʌlt/", pos: "n./adj.", translation: "成年人；成年的", level: "CET-4", example: { en: "He is an adult now.", cn: "他现在是成年人了。" } },
  "advance": { word: "advance", phonetic: "/ədˈvæns/", pos: "v./n.", translation: "前进，进步", level: "CET-4", example: { en: "Technology continues to advance.", cn: "科技不断进步。" } },
  "advantage": { word: "advantage", phonetic: "/ədˈvæntɪdʒ/", pos: "n.", translation: "优势，有利条件", level: "CET-4", example: { en: "His experience gives him an advantage.", cn: "他的经验给了他优势。" } },
  "adventure": { word: "adventure", phonetic: "/ədˈventʃər/", pos: "n.", translation: "冒险，奇遇", level: "CET-4", example: { en: "Life is an adventure.", cn: "人生是一场冒险。" } },
  "advertise": { word: "advertise", phonetic: "/ˈædvərtaɪz/", pos: "v.", translation: "做广告，宣传", level: "CET-4", example: { en: "They advertise their products online.", cn: "他们在网上宣传产品。" } },
  "advice": { word: "advice", phonetic: "/ədˈvaɪs/", pos: "n.", translation: "建议，劝告", level: "CET-4", example: { en: "Thank you for your advice.", cn: "谢谢你的建议。" } },
  "advise": { word: "advise", phonetic: "/ədˈvaɪz/", pos: "v.", translation: "建议，劝告", level: "CET-4", example: { en: "I advise you to take a rest.", cn: "我建议你休息一下。" } },
  "affair": { word: "affair", phonetic: "/əˈfer/", pos: "n.", translation: "事务，事件", level: "CET-4", example: { en: "That's a private affair.", cn: "那是私事。" } },
  "affect": { word: "affect", phonetic: "/əˈfekt/", pos: "v.", translation: "影响，感动", level: "CET-4", example: { en: "The weather affects my mood.", cn: "天气影响我的心情。" } },
  "afford": { word: "afford", phonetic: "/əˈfɔːrd/", pos: "v.", translation: "负担得起，提供", level: "CET-4", example: { en: "I can't afford a new car.", cn: "我买不起新车。" } },
  "afraid": { word: "afraid", phonetic: "/əˈfreɪd/", pos: "adj.", translation: "害怕的，恐怕", level: "CET-4", example: { en: "Don't be afraid of failure.", cn: "不要害怕失败。" } },
  "after": { word: "after", phonetic: "/ˈæftər/", pos: "prep./conj.", translation: "在...之后", level: "CET-4", example: { en: "Let's meet after work.", cn: "下班后见。" } },
  "afternoon": { word: "afternoon", phonetic: "/ˌæftərˈnuːn/", pos: "n.", translation: "下午", level: "CET-4", example: { en: "I have a meeting this afternoon.", cn: "今天下午我有个会议。" } },
  "again": { word: "again", phonetic: "/əˈɡen/", pos: "adv.", translation: "再次，又", level: "CET-4", example: { en: "Please try again.", cn: "请再试一次。" } },
  "against": { word: "against", phonetic: "/əˈɡenst/", pos: "prep.", translation: "反对，靠着", level: "CET-4", example: { en: "We are against the plan.", cn: "我们反对这个计划。" } },
  "age": { word: "age", phonetic: "/eɪdʒ/", pos: "n./v.", translation: "年龄；变老", level: "CET-4", example: { en: "What is your age?", cn: "你多大了？" } },
  "agency": { word: "agency", phonetic: "/ˈeɪdʒənsi/", pos: "n.", translation: "代理，机构", level: "CET-4", example: { en: "She works for a travel agency.", cn: "她在一家旅行社工作。" } },
  "agent": { word: "agent", phonetic: "/ˈeɪdʒənt/", pos: "n.", translation: "代理人，代理商", level: "CET-4", example: { en: "He is a travel agent.", cn: "他是个旅行代理商。" } },
  "agree": { word: "agree", phonetic: "/əˈɡriː/", pos: "v.", translation: "同意，赞同", level: "CET-4", example: { en: "I agree with your opinion.", cn: "我同意你的观点。" } },
  "agreement": { word: "agreement", phonetic: "/əˈɡriːmənt/", pos: "n.", translation: "协议，同意", level: "CET-4", example: { en: "We reached an agreement.", cn: "我们达成了协议。" } },
  "ahead": { word: "ahead", phonetic: "/əˈhed/", pos: "adv.", translation: "向前，在前面", level: "CET-4", example: { en: "Go straight ahead.", cn: "一直往前走。" } },
  "aid": { word: "aid", phonetic: "/eɪd/", pos: "n./v.", translation: "帮助，援助", level: "CET-4", example: { en: "They provided aid to the victims.", cn: "他们向受害者提供了援助。" } },
  "aim": { word: "aim", phonetic: "/eɪm/", pos: "v./n.", translation: "瞄准；目标", level: "CET-4", example: { en: "What is your aim in life?", cn: "你的人生目标是什么？" } },
  "air": { word: "air", phonetic: "/er/", pos: "n.", translation: "空气，天空", level: "CET-4", example: { en: "Fresh air is good for health.", cn: "新鲜空气对健康有益。" } },
  "aircraft": { word: "aircraft", phonetic: "/ˈerkræft/", pos: "n.", translation: "飞机，航空器", level: "CET-4", example: { en: "The aircraft landed safely.", cn: "飞机安全着陆。" } },
  "airline": { word: "airline", phonetic: "/ˈerlaɪn/", pos: "n.", translation: "航空公司", level: "CET-4", example: { en: "Which airline do you prefer?", cn: "你喜欢哪家航空公司？" } },
  "airport": { word: "airport", phonetic: "/ˈerpɔːrt/", pos: "n.", translation: "机场", level: "CET-4", example: { en: "I will meet you at the airport.", cn: "我会在机场接你。" } },
  "alarm": { word: "alarm", phonetic: "/əˈlɑːrm/", pos: "n./v.", translation: "警报；使惊恐", level: "CET-4", example: { en: "The alarm clock woke me up.", cn: "闹钟把我叫醒了。" } },
  "album": { word: "album", phonetic: "/ˈælbəm/", pos: "n.", translation: "相册，专辑", level: "CET-4", example: { en: "This is a photo album.", cn: "这是一本相册。" } },
  "alcohol": { word: "alcohol", phonetic: "/ˈælkəhɔːl/", pos: "n.", translation: "酒精，酒", level: "CET-4", example: { en: "Alcohol is bad for health.", cn: "酒精对健康有害。" } },
  "alike": { word: "alike", phonetic: "/əˈlaɪk/", pos: "adj./adv.", translation: "相似的（地）", level: "CET-4", example: { en: "The two sisters look alike.", cn: "这两姐妹看起来很像。" } },
  "alive": { word: "alive", phonetic: "/əˈlaɪv/", pos: "adj.", translation: "活着的，有活力的", level: "CET-4", example: { en: "Is she still alive?", cn: "她还活着吗？" } },
  "allow": { word: "allow", phonetic: "/əˈlaʊ/", pos: "v.", translation: "允许，准许", level: "CET-4", example: { en: "Smoking is not allowed here.", cn: "这里不允许吸烟。" } },
  "almost": { word: "almost", phonetic: "/ˈɔːlmoʊst/", pos: "adv.", translation: "几乎，差不多", level: "CET-4", example: { en: "It's almost time.", cn: "差不多是时候了。" } },
  "alone": { word: "alone", phonetic: "/əˈloʊn/", pos: "adj./adv.", translation: "单独的，独自", level: "CET-4", example: { en: "She lives alone.", cn: "她独自生活。" } },
  "along": { word: "along", phonetic: "/əˈlɔːŋ/", pos: "prep./adv.", translation: "沿着，一起", level: "CET-4", example: { en: "Walk along the river.", cn: "沿着河边走。" } },
  "already": { word: "already", phonetic: "/ɔːlˈredi/", pos: "adv.", translation: "已经", level: "CET-4", example: { en: "I have already finished my homework.", cn: "我已经完成作业了。" } },
  "also": { word: "also", phonetic: "/ˈɔːlsoʊ/", pos: "adv.", translation: "也，同样", level: "CET-4", example: { en: "She also likes music.", cn: "她也喜欢音乐。" } },
  "alter": { word: "alter", phonetic: "/ˈɔːltər/", pos: "v.", translation: "改变，修改", level: "CET-4", example: { en: "You should alter your plan.", cn: "你应该改变你的计划。" } },
  "alternative": { word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", pos: "n./adj.", translation: "替代品；替代的", level: "CET-4", example: { en: "Is there an alternative solution?", cn: "有没有替代解决方案？" } },
  "although": { word: "although", phonetic: "/ɔːlˈðoʊ/", pos: "conj.", translation: "虽然，尽管", level: "CET-4", example: { en: "Although it was raining, we went out.", cn: "虽然下雨，我们还是出去了。" } },
  "always": { word: "always", phonetic: "/ˈɔːlweɪz/", pos: "adv.", translation: "总是，一直", level: "CET-4", example: { en: "He is always late.", cn: "他总是迟到。" } },
  "amaze": { word: "amaze", phonetic: "/əˈmeɪz/", pos: "v.", translation: "使惊奇，使惊叹", level: "CET-4", example: { en: "Her talent never ceases to amaze me.", cn: "她的才华总是让我惊叹。" } },
  "ambition": { word: "ambition", phonetic: "/æmˈbɪʃn/", pos: "n.", translation: "雄心，野心", level: "CET-4", example: { en: "She has great ambition.", cn: "她有很大的抱负。" } },
  "ambulance": { word: "ambulance", phonetic: "/ˈæmbjələns/", pos: "n.", translation: "救护车", level: "CET-4", example: { en: "Call an ambulance!", cn: "快叫救护车！" } },
  "amount": { word: "amount", phonetic: "/əˈmaʊnt/", pos: "n./v.", translation: "数量；总计", level: "CET-4", example: { en: "A large amount of money was stolen.", cn: "一大笔钱被偷了。" } },
  "amuse": { word: "amuse", phonetic: "/əˈmjuːz/", pos: "v.", translation: "使愉快，逗笑", level: "CET-4", example: { en: "The clown amused the children.", cn: "小丑逗笑了孩子们。" } },
  "analyze": { word: "analyze", phonetic: "/ˈænəlaɪz/", pos: "v.", translation: "分析", level: "CET-4", example: { en: "We need to analyze the data.", cn: "我们需要分析数据。" } },
  "ancient": { word: "ancient", phonetic: "/ˈeɪnʃənt/", pos: "adj.", translation: "古代的，古老的", level: "CET-4", example: { en: "The ancient ruins attract many tourists.", cn: "古老的遗址吸引了很多游客。" } },
  "anger": { word: "anger", phonetic: "/ˈæŋɡər/", pos: "n./v.", translation: "愤怒；使发怒", level: "CET-4", example: { en: "He couldn't hide his anger.", cn: "他无法掩饰自己的愤怒。" } },
  "angle": { word: "angle", phonetic: "/ˈæŋɡl/", pos: "n.", translation: "角度，角", level: "CET-4", example: { en: "The angle is 90 degrees.", cn: "角度是90度。" } },
  "angry": { word: "angry", phonetic: "/ˈæŋɡri/", pos: "adj.", translation: "生气的，愤怒的", level: "CET-4", example: { en: "Don't be angry with me.", cn: "别生我的气。" } },
  "animal": { word: "animal", phonetic: "/ˈænɪml/", pos: "n.", translation: "动物", level: "CET-4", example: { en: "Dogs are loyal animals.", cn: "狗是忠诚的动物。" } },
  "announce": { word: "announce", phonetic: "/əˈnaʊns/", pos: "v.", translation: "宣布，宣告", level: "CET-4", example: { en: "They announced the winner.", cn: "他们宣布了获胜者。" } },
  "annoy": { word: "annoy", phonetic: "/əˈnɔɪ/", pos: "v.", translation: "使恼怒，打扰", level: "CET-4", example: { en: "The noise annoys me.", cn: "噪音打扰我。" } },
  "annual": { word: "annual", phonetic: "/ˈænjuəl/", pos: "adj.", translation: "每年的，年度的", level: "CET-4", example: { en: "The annual meeting will be held next week.", cn: "年度会议将于下周举行。" } },
  "another": { word: "another", phonetic: "/əˈnʌðər/", pos: "adj./pron.", translation: "另一个，又一个", level: "CET-4", example: { en: "Would you like another cup of tea?", cn: "你想再来一杯茶吗？" } },
  "answer": { word: "answer", phonetic: "/ˈænsər/", pos: "n./v.", translation: "回答，答案", level: "CET-4", example: { en: "Can you answer my question?", cn: "你能回答我的问题吗？" } },
  "anticipate": { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", pos: "v.", translation: "预期，预料", level: "CET-6", example: { en: "I anticipate problems.", cn: "我预料会有问题。" } },
  "anxiety": { word: "anxiety", phonetic: "/æŋˈzaɪəti/", pos: "n.", translation: "焦虑，忧虑", level: "CET-4", example: { en: "She felt great anxiety before the exam.", cn: "考试前她感到非常焦虑。" } },
  "anxious": { word: "anxious", phonetic: "/ˈæŋkʃəs/", pos: "adj.", translation: "焦虑的，担忧的", level: "CET-4", example: { en: "I'm anxious about the result.", cn: "我对结果感到焦虑。" } },
  "any": { word: "any", phonetic: "/ˈeni/", pos: "adj./pron.", translation: "任何的，一些", level: "CET-4", example: { en: "Do you have any questions?", cn: "你有什么问题吗？" } },
  "anybody": { word: "anybody", phonetic: "/ˈenibɑːdi/", pos: "pron.", translation: "任何人", level: "CET-4", example: { en: "Is anybody home?", cn: "有人在家吗？" } },
  "anyone": { word: "anyone", phonetic: "/ˈeniwʌn/", pos: "pron.", translation: "任何人", level: "CET-4", example: { en: "Can anyone help me?", cn: "有人能帮我吗？" } },
  "anything": { word: "anything", phonetic: "/ˈeniθɪŋ/", pos: "pron.", translation: "任何事", level: "CET-4", example: { en: "You can buy anything you want.", cn: "你可以买任何你想要的东西。" } },
  "anyway": { word: "anyway", phonetic: "/ˈeniweɪ/", pos: "adv.", translation: "无论如何，反正", level: "CET-4", example: { en: "I don't like it, but I'll do it anyway.", cn: "我不喜欢，但不管怎样我还是会做。" } },
  "anywhere": { word: "anywhere", phonetic: "/ˈeniwer/", pos: "adv.", translation: "任何地方", level: "CET-4", example: { en: "You can go anywhere you like.", cn: "你可以去任何你想去的地方。" } },
  "apart": { word: "apart", phonetic: "/əˈpɑːrt/", pos: "adv.", translation: "分开，相距", level: "CET-4", example: { en: "The two houses are far apart.", cn: "两座房子相距很远。" } },
  "apartment": { word: "apartment", phonetic: "/əˈpɑːrtmənt/", pos: "n.", translation: "公寓", level: "CET-4", example: { en: "She lives in a small apartment.", cn: "她住在一间小公寓里。" } },
  "apologize": { word: "apologize", phonetic: "/əˈpɑːlədʒaɪz/", pos: "v.", translation: "道歉", level: "CET-4", example: { en: "I apologize for being late.", cn: "我为迟到道歉。" } },
  "apparent": { word: "apparent", phonetic: "/əˈpærənt/", pos: "adj.", translation: "明显的，表面上的", level: "CET-4", example: { en: "It is apparent that he is lying.", cn: "很明显他在说谎。" } },
  "appeal": { word: "appeal", phonetic: "/əˈpiːl/", pos: "v./n.", translation: "呼吁，吸引", level: "CET-4", example: { en: "The design appeals to young people.", cn: "这个设计吸引年轻人。" } },
  "appear": { word: "appear", phonetic: "/əˈpɪr/", pos: "v.", translation: "出现，显得", level: "CET-4", example: { en: "The sun appeared from behind the clouds.", cn: "太阳从云后出现了。" } },
  "appetite": { word: "appetite", phonetic: "/ˈæpɪtaɪt/", pos: "n.", translation: "食欲，胃口", level: "CET-4", example: { en: "Exercise gives me a good appetite.", cn: "运动让我胃口很好。" } },
  "applaud": { word: "applaud", phonetic: "/əˈplɔːd/", pos: "v.", translation: "鼓掌，称赞", level: "CET-4", example: { en: "The audience applauded loudly.", cn: "观众热烈鼓掌。" } },
  "apple": { word: "apple", phonetic: "/ˈæpl/", pos: "n.", translation: "苹果", level: "CET-4", example: { en: "An apple a day keeps the doctor away.", cn: "一天一苹果，医生远离我。" } },
  "apply": { word: "apply", phonetic: "/əˈplaɪ/", pos: "v.", translation: "申请，应用", level: "CET-4", example: { en: "I will apply for the job.", cn: "我会申请这份工作。" } },
  "appoint": { word: "appoint", phonetic: "/əˈpɔɪnt/", pos: "v.", translation: "任命，指定", level: "CET-4", example: { en: "They appointed him as manager.", cn: "他们任命他为经理。" } },
  "appreciate": { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", pos: "v.", translation: "欣赏，感激", level: "CET-4", example: { en: "I appreciate your help.", cn: "我感谢你的帮助。" } },
  "approach": { word: "approach", phonetic: "/əˈproʊtʃ/", pos: "v./n.", translation: "接近，方法", level: "CET-4", example: { en: "We need a new approach to this problem.", cn: "我们需要解决这个问题的新方法。" } },
  "appropriate": { word: "appropriate", phonetic: "/əˈproʊpriət/", pos: "adj.", translation: "适当的，合适的", level: "CET-4", example: { en: "This is not appropriate for children.", cn: "这不适合儿童。" } },
  "approve": { word: "approve", phonetic: "/əˈpruːv/", pos: "v.", translation: "批准，赞成", level: "CET-4", example: { en: "The plan was approved by the board.", cn: "计划被董事会批准了。" } },
  "approximate": { word: "approximate", phonetic: "/əˈprɑːksɪmət/", pos: "adj.", translation: "大约的，近似的", level: "CET-6", example: { en: "What is the approximate cost?", cn: "大概费用是多少？" } },
  "architect": { word: "architect", phonetic: "/ˈɑːrkɪtekt/", pos: "n.", translation: "建筑师", level: "CET-4", example: { en: "The architect designed a beautiful house.", cn: "建筑师设计了一座漂亮的房子。" } },
  "architecture": { word: "architecture", phonetic: "/ˈɑːrkɪtektʃər/", pos: "n.", translation: "建筑学", level: "CET-4", example: { en: "She studied architecture at university.", cn: "她在大学学习建筑学。" } },
  "area": { word: "area", phonetic: "/ˈeriə/", pos: "n.", translation: "地区，面积", level: "CET-4", example: { en: "What is the area of this room?", cn: "这个房间的面积是多少？" } },
  "argue": { word: "argue", phonetic: "/ˈɑːrɡjuː/", pos: "v.", translation: "争论，辩论", level: "CET-4", example: { en: "They argued about the decision.", cn: "他们对这个决定争论不休。" } },
  "argument": { word: "argument", phonetic: "/ˈɑːrɡjumənt/", pos: "n.", translation: "争论，论点", level: "CET-4", example: { en: "I don't want to have an argument.", cn: "我不想争论。" } },
  "arise": { word: "arise", phonetic: "/əˈraɪz/", pos: "v.", translation: "出现，产生", level: "CET-4", example: { en: "Problems arise when we don't communicate.", cn: "不沟通时问题就会出现。" } },
  "arm": { word: "arm", phonetic: "/ɑːrm/", pos: "n./v.", translation: "手臂；武装", level: "CET-4", example: { en: "She carried a book under her arm.", cn: "她腋下夹着一本书。" } },
  "army": { word: "army", phonetic: "/ˈɑːrmi/", pos: "n.", translation: "军队，陆军", level: "CET-4", example: { en: "He served in the army for ten years.", cn: "他在军队服役十年。" } },
  "around": { word: "around", phonetic: "/əˈraʊnd/", pos: "prep./adv.", translation: "在...周围，大约", level: "CET-4", example: { en: "The children sat around the table.", cn: "孩子们围坐在桌旁。" } },
  "arrange": { word: "arrange", phonetic: "/əˈreɪndʒ/", pos: "v.", translation: "安排，整理", level: "CET-4", example: { en: "I will arrange a meeting.", cn: "我会安排一次会议。" } },
  "arrangement": { word: "arrangement", phonetic: "/əˈreɪndʒmənt/", pos: "n.", translation: "安排，布置", level: "CET-4", example: { en: "They made arrangements for the trip.", cn: "他们为旅行做了安排。" } },
  "arrest": { word: "arrest", phonetic: "/əˈrest/", pos: "v./n.", translation: "逮捕，拘留", level: "CET-4", example: { en: "The police arrested the suspect.", cn: "警察逮捕了嫌疑人。" } },
  "arrival": { word: "arrival", phonetic: "/əˈraɪvl/", pos: "n.", translation: "到达，到来", level: "CET-4", example: { en: "We await your arrival.", cn: "我们等待您的到来。" } },
  "arrive": { word: "arrive", phonetic: "/əˈraɪv/", pos: "v.", translation: "到达，抵达", level: "CET-4", example: { en: "We will arrive at the station at noon.", cn: "我们将在中午到达车站。" } },
  "arrow": { word: "arrow", phonetic: "/ˈæroʊ/", pos: "n.", translation: "箭，箭头", level: "CET-4", example: { en: "He shot an arrow at the target.", cn: "他向靶子射了一箭。" } },
  "article": { word: "article", phonetic: "/ˈɑːrtɪkl/", pos: "n.", translation: "文章，物品", level: "CET-4", example: { en: "I read an interesting article.", cn: "我读了一篇有趣的文章。" } },
  "artificial": { word: "artificial", phonetic: "/ˌɑːrtɪˈfɪʃl/", pos: "adj.", translation: "人工的，人造的", level: "CET-4", example: { en: "Artificial intelligence is advancing rapidly.", cn: "人工智能正在快速发展。" } },
  "artist": { word: "artist", phonetic: "/ˈɑːrtɪst/", pos: "n.", translation: "艺术家", level: "CET-4", example: { en: "The artist painted a beautiful picture.", cn: "艺术家画了一幅美丽的画。" } },
  "artistic": { word: "artistic", phonetic: "/ɑːrˈtɪstɪk/", pos: "adj.", translation: "艺术的，有艺术感的", level: "CET-4", example: { en: "She has an artistic temperament.", cn: "她有艺术气质。" } },
  "aside": { word: "aside", phonetic: "/əˈsaɪd/", pos: "adv.", translation: "在一边，到旁边", level: "CET-4", example: { en: "Put it aside for later.", cn: "把它放在一边以后用。" } },
  "ask": { word: "ask", phonetic: "/æsk/", pos: "v.", translation: "问，要求", level: "CET-4", example: { en: "May I ask a question?", cn: "我可以问一个问题吗？" } },
  "asleep": { word: "asleep", phonetic: "/əˈsliːp/", pos: "adj.", translation: "睡着的", level: "CET-4", example: { en: "The baby is asleep.", cn: "宝宝睡着了。" } },
  "aspect": { word: "aspect", phonetic: "/ˈæspekt/", pos: "n.", translation: "方面，层面", level: "CET-4", example: { en: "We considered every aspect of the problem.", cn: "我们考虑了问题的各个方面。" } },
  "assemble": { word: "assemble", phonetic: "/əˈsembl/", pos: "v.", translation: "集合，组装", level: "CET-4", example: { en: "The students assembled in the hall.", cn: "学生们在大厅集合。" } },
  "assert": { word: "assert", phonetic: "/əˈsɜːrt/", pos: "v.", translation: "断言，声称", level: "CET-6", example: { en: "He asserted his innocence.", cn: "他声称自己是无辜的。" } },
  "assess": { word: "assess", phonetic: "/əˈses/", pos: "v.", translation: "评估，评价", level: "CET-4", example: { en: "The teacher will assess your progress.", cn: "老师会评估你的进步。" } },
  "assign": { word: "assign", phonetic: "/əˈsaɪn/", pos: "v.", translation: "分配，指定", level: "CET-4", example: { en: "The teacher assigned homework to us.", cn: "老师给我们布置了作业。" } },
  "assist": { word: "assist", phonetic: "/əˈsɪst/", pos: "v.", translation: "帮助，协助", level: "CET-4", example: { en: "Can I assist you with anything?", cn: "需要我帮什么忙吗？" } },
  "assistance": { word: "assistance", phonetic: "/əˈsɪstəns/", pos: "n.", translation: "帮助，援助", level: "CET-4", example: { en: "Thank you for your assistance.", cn: "谢谢你的帮助。" } },
  "assistant": { word: "assistant", phonetic: "/əˈsɪstənt/", pos: "n.", translation: "助手，助理", level: "CET-4", example: { en: "She works as a teaching assistant.", cn: "她担任助教。" } },
  "associate": { word: "associate", phonetic: "/əˈsoʊʃieɪt/", pos: "v./n.", translation: "联系，关联；同事", level: "CET-4", example: { en: "I always associate summer with ice cream.", cn: "我总是把夏天和冰淇淋联系在一起。" } },
  "association": { word: "association", phonetic: "/əˌsoʊsiˈeɪʃn/", pos: "n.", translation: "协会，关联", level: "CET-4", example: { en: "He is a member of the association.", cn: "他是协会的成员。" } },
  "assume": { word: "assume", phonetic: "/əˈsuːm/", pos: "v.", translation: "假设，承担", level: "CET-4", example: { en: "I assume you are right.", cn: "我假设你是对的。" } },
  "assure": { word: "assure", phonetic: "/əˈʃʊr/", pos: "v.", translation: "向...保证，使确信", level: "CET-4", example: { en: "I assure you of my support.", cn: "我向你保证我会支持你。" } },
  "astonish": { word: "astonish", phonetic: "/əˈstɑːnɪʃ/", pos: "v.", translation: "使惊讶", level: "CET-4", example: { en: "The news astonished everyone.", cn: "这个消息让所有人都很惊讶。" } },
  "athlete": { word: "athlete", phonetic: "/ˈæθliːt/", pos: "n.", translation: "运动员", level: "CET-4", example: { en: "The athlete won a gold medal.", cn: "运动员获得了一枚金牌。" } },
  "atmosphere": { word: "atmosphere", phonetic: "/ˈætməsfɪr/", pos: "n.", translation: "气氛，大气", level: "CET-4", example: { en: "The restaurant has a romantic atmosphere.", cn: "这家餐厅气氛浪漫。" } },
  "attach": { word: "attach", phonetic: "/əˈtætʃ/", pos: "v.", translation: "附上，系上", level: "CET-4", example: { en: "Please attach the file to your email.", cn: "请把文件附在邮件里。" } },
  "attack": { word: "attack", phonetic: "/əˈtæk/", pos: "v./n.", translation: "攻击，进攻", level: "CET-4", example: { en: "The enemy launched an attack.", cn: "敌人发动了进攻。" } },
  "attempt": { word: "attempt", phonetic: "/əˈtempt/", pos: "v./n.", translation: "尝试，试图", level: "CET-4", example: { en: "I will attempt to solve this problem.", cn: "我会尝试解决这个问题。" } },
  "attend": { word: "attend", phonetic: "/əˈtend/", pos: "v.", translation: "参加，出席", level: "CET-4", example: { en: "All students must attend the meeting.", cn: "所有学生必须参加会议。" } },
  "attention": { word: "attention", phonetic: "/əˈtenʃn/", pos: "n.", translation: "注意，注意力", level: "CET-4", example: { en: "Pay attention to the teacher.", cn: "专心听老师讲课。" } },
  "attitude": { word: "attitude", phonetic: "/ˈætɪtuːd/", pos: "n.", translation: "态度，看法", level: "CET-4", example: { en: "A positive attitude is important.", cn: "积极的态度很重要。" } },
  "attorney": { word: "attorney", phonetic: "/əˈtɜːrni/", pos: "n.", translation: "律师，代理人", level: "CET-4", example: { en: "He hired an attorney.", cn: "他聘请了一位律师。" } },
  "attract": { word: "attract", phonetic: "/əˈtrækt/", pos: "v.", translation: "吸引", level: "CET-4", example: { en: "The bright colors attract children.", cn: "鲜艳的颜色吸引孩子。" } },
  "authority": { word: "authority", phonetic: "/əˈθɔːrəti/", pos: "n.", translation: "权威，权力", level: "CET-4", example: { en: "He is an authority on ancient history.", cn: "他是古代史方面的权威。" } },
  "automatic": { word: "automatic", phonetic: "/ˌɔːtəˈmætɪk/", pos: "adj.", translation: "自动的", level: "CET-4", example: { en: "This is an automatic washing machine.", cn: "这是一台自动洗衣机。" } },
  "available": { word: "available", phonetic: "/əˈveɪləbl/", pos: "adj.", translation: "可用的，可获得的", level: "CET-4", example: { en: "The book is available online.", cn: "这本书可以在网上找到。" } },
  "average": { word: "average", phonetic: "/ˈævərɪdʒ/", pos: "adj./n.", translation: "平均的；平均值", level: "CET-4", example: { en: "The average temperature is 25 degrees.", cn: "平均温度是25度。" } },
  "avoid": { word: "avoid", phonetic: "/əˈvɔɪd/", pos: "v.", translation: "避免，回避", level: "CET-4", example: { en: "Try to avoid junk food.", cn: "尽量避免垃圾食品。" } },
  "awake": { word: "awake", phonetic: "/əˈweɪk/", pos: "adj./v.", translation: "醒着的；唤醒", level: "CET-4", example: { en: "I am still awake.", cn: "我还醒着。" } },
  "award": { word: "award", phonetic: "/əˈwɔːrd/", pos: "n./v.", translation: "奖励；授予", level: "CET-4", example: { en: "She won the award for best actress.", cn: "她获得了最佳女演员奖。" } },
  "aware": { word: "aware", phonetic: "/əˈwer/", pos: "adj.", translation: "意识到的，知道的", level: "CET-4", example: { en: "I am aware of the risks.", cn: "我知道风险。" } },
  "away": { word: "away", phonetic: "/əˈweɪ/", pos: "adv.", translation: "离开，远离", level: "CET-4", example: { en: "Go away!", cn: "走开！" } },
  "awful": { word: "awful", phonetic: "/ˈɔːfl/", pos: "adj.", translation: "糟糕的，可怕的", level: "CET-4", example: { en: "The weather was awful.", cn: "天气糟透了。" } },
  "awkward": { word: "awkward", phonetic: "/ˈɔːkwərd/", pos: "adj.", translation: "尴尬的，笨拙的", level: "CET-4", example: { en: "There was an awkward silence.", cn: "有一阵尴尬的沉默。" } },
  "baby": { word: "baby", phonetic: "/ˈbeɪbi/", pos: "n.", translation: "婴儿", level: "CET-4", example: { en: "The baby is sleeping.", cn: "宝宝正在睡觉。" } },
  "back": { word: "back", phonetic: "/bæk/", pos: "n./adv.", translation: "背部；后面", level: "CET-4", example: { en: "Sit back and relax.", cn: "向后靠放松一下。" } },
  "background": { word: "background", phonetic: "/ˈbækɡraʊnd/", pos: "n.", translation: "背景", level: "CET-4", example: { en: "What is your background?", cn: "你的背景是什么？" } },
  "bacteria": { word: "bacteria", phonetic: "/bækˈtɪriə/", pos: "n.", translation: "细菌", level: "CET-6", example: { en: "Bacteria can cause infections.", cn: "细菌会引起感染。" } },
  "bad": { word: "bad", phonetic: "/bæd/", pos: "adj.", translation: "坏的，不好的", level: "CET-4", example: { en: "This is bad news.", cn: "这是个坏消息。" } },
  "badly": { word: "badly", phonetic: "/ˈbædli/", pos: "adv.", translation: "坏地，严重地", level: "CET-4", example: { en: "He was badly injured.", cn: "他受了重伤。" } },
  "bag": { word: "bag", phonetic: "/bæɡ/", pos: "n.", translation: "袋子，包", level: "CET-4", example: { en: "I need a shopping bag.", cn: "我需要一个购物袋。" } },
  "balance": { word: "balance", phonetic: "/ˈbæləns/", pos: "n./v.", translation: "平衡；权衡", level: "CET-4", example: { en: "Work-life balance is important.", cn: "工作与生活的平衡很重要。" } },
  "ball": { word: "ball", phonetic: "/bɔːl/", pos: "n.", translation: "球，舞会", level: "CET-4", example: { en: "The children are playing with a ball.", cn: "孩子们在玩球。" } },
  "ban": { word: "ban", phonetic: "/bæn/", pos: "v./n.", translation: "禁止，取缔", level: "CET-4", example: { en: "Smoking is banned in public places.", cn: "公共场所禁止吸烟。" } },
  "banana": { word: "banana", phonetic: "/bəˈnænə/", pos: "n.", translation: "香蕉", level: "CET-4", example: { en: "I like eating bananas.", cn: "我喜欢吃香蕉。" } },
  "band": { word: "band", phonetic: "/bænd/", pos: "n.", translation: "乐队，带子", level: "CET-4", example: { en: "The band played at the concert.", cn: "乐队在音乐会上演奏。" } },
  "bank": { word: "bank", phonetic: "/bæŋk/", pos: "n.", translation: "银行，河岸", level: "CET-4", example: { en: "I need to go to the bank.", cn: "我需要去银行。" } },
  "bar": { word: "bar", phonetic: "/bɑːr/", pos: "n.", translation: "酒吧，棒条", level: "CET-4", example: { en: "Let's meet at the bar.", cn: "我们在酒吧见面吧。" } },
  "barrier": { word: "barrier", phonetic: "/ˈbæriər/", pos: "n.", translation: "障碍，屏障", level: "CET-4", example: { en: "Language barrier is a common problem.", cn: "语言障碍是常见问题。" } },
  "base": { word: "base", phonetic: "/beɪs/", pos: "n./v.", translation: "基础；基于", level: "CET-4", example: { en: "This is the base of the pyramid.", cn: "这是金字塔的底部。" } },
  "basic": { word: "basic", phonetic: "/ˈbeɪsɪk/", pos: "adj.", translation: "基本的，基础的", level: "CET-4", example: { en: "Learning basic skills is important.", cn: "学习基本技能很重要。" } },
  "basin": { word: "basin", phonetic: "/ˈbeɪsn/", pos: "n.", translation: "盆地，水盆", level: "CET-4", example: { en: "Wash your hands in the basin.", cn: "在水盆里洗手。" } },
  "basis": { word: "basis", phonetic: "/ˈbeɪsɪs/", pos: "n.", translation: "基础，根据", level: "CET-4", example: { en: "On the basis of these facts.", cn: "基于这些事实。" } },
  "basket": { word: "basket", phonetic: "/ˈbæskɪt/", pos: "n.", translation: "篮子", level: "CET-4", example: { en: "She carried a basket of fruits.", cn: "她提着一篮水果。" } },
  "basketball": { word: "basketball", phonetic: "/ˈbæskɪtbɔːl/", pos: "n.", translation: "篮球", level: "CET-4", example: { en: "Let's play basketball.", cn: "我们打篮球吧。" } },
  "bath": { word: "bath", phonetic: "/bæθ/", pos: "n.", translation: "沐浴，浴缸", level: "CET-4", example: { en: "I take a hot bath every night.", cn: "我每晚都洗热水澡。" } },
  "bathroom": { word: "bathroom", phonetic: "/ˈbæθruːm/", pos: "n.", translation: "浴室，卫生间", level: "CET-4", example: { en: "Where is the bathroom?", cn: "洗手间在哪里？" } },
  "battery": { word: "battery", phonetic: "/ˈbætəri/", pos: "n.", translation: "电池", level: "CET-4", example: { en: "The battery is dead.", cn: "电池没电了。" } },
  "battle": { word: "battle", phonetic: "/ˈbætl/", pos: "n./v.", translation: "战斗，战役", level: "CET-4", example: { en: "The battle lasted for three days.", cn: "战斗持续了三天。" } },
  "beach": { word: "beach", phonetic: "/biːtʃ/", pos: "n.", translation: "海滩，沙滩", level: "CET-4", example: { en: "We spent the day at the beach.", cn: "我们在海滩度过了一天。" } },
  "bean": { word: "bean", phonetic: "/biːn/", pos: "n.", translation: "豆，豆类", level: "CET-4", example: { en: "Coffee beans are imported.", cn: "咖啡豆是进口的。" } },
  "bear": { word: "bear", phonetic: "/ber/", pos: "n./v.", translation: "熊；承受", level: "CET-4", example: { en: "The bear is a large animal.", cn: "熊是一种大型动物。" } },
  "beard": { word: "beard", phonetic: "/bɪrd/", pos: "n.", translation: "胡须", level: "CET-4", example: { en: "He has a long beard.", cn: "他留着长胡子。" } },
  "beat": { word: "beat", phonetic: "/biːt/", pos: "v./n.", translation: "敲打，击败", level: "CET-4", example: { en: "Our team beat them 3-1.", cn: "我们队以3-1击败了他们。" } },
  "beautiful": { word: "beautiful", phonetic: "/ˈbjuːtɪfl/", pos: "adj.", translation: "美丽的，美好的", level: "CET-4", example: { en: "She is a beautiful girl.", cn: "她是个美丽的女孩。" } },
  "beauty": { word: "beauty", phonetic: "/ˈbjuːti/", pos: "n.", translation: "美丽，美人", level: "CET-4", example: { en: "Beauty is in the eye of the beholder.", cn: "情人眼里出西施。" } },
  "because": { word: "because", phonetic: "/bɪˈkɔːz/", pos: "conj.", translation: "因为", level: "CET-4", example: { en: "I love her because she is kind.", cn: "我爱她，因为她很善良。" } },
  "become": { word: "become", phonetic: "/bɪˈkʌm/", pos: "v.", translation: "变成，成为", level: "CET-4", example: { en: "He wants to become a doctor.", cn: "他想成为一名医生。" } },
  "bed": { word: "bed", phonetic: "/bed/", pos: "n.", translation: "床", level: "CET-4", example: { en: "It's time for bed.", cn: "该睡觉了。" } },
  "bedroom": { word: "bedroom", phonetic: "/ˈbedruːm/", pos: "n.", translation: "卧室", level: "CET-4", example: { en: "The bedroom is on the second floor.", cn: "卧室在二楼。" } },
  "bee": { word: "bee", phonetic: "/biː/", pos: "n.", translation: "蜜蜂", level: "CET-4", example: { en: "A bee can make honey.", cn: "蜜蜂能酿蜜。" } },
  "beef": { word: "beef", phonetic: "/biːf/", pos: "n.", translation: "牛肉", level: "CET-4", example: { en: "I prefer beef to pork.", cn: "比起猪肉我更喜欢牛肉。" } },
  "beer": { word: "beer", phonetic: "/bɪr/", pos: "n.", translation: "啤酒", level: "CET-4", example: { en: "Would you like a beer?", cn: "你想喝啤酒吗？" } },
  "before": { word: "before", phonetic: "/bɪˈfɔːr/", pos: "prep./conj.", translation: "在...之前", level: "CET-4", example: { en: "I had dinner before the movie.", cn: "我在看电影前吃了晚饭。" } },
  "begin": { word: "begin", phonetic: "/bɪˈɡɪn/", pos: "v.", translation: "开始", level: "CET-4", example: { en: "Let's begin the meeting.", cn: "让我们开始会议吧。" } },
  "behalf": { word: "behalf", phonetic: "/bɪˈhæf/", pos: "n.", translation: "代表，利益", level: "CET-4", example: { en: "On behalf of our team, thank you.", cn: "代表我们团队谢谢你。" } },
  "behavior": { word: "behavior", phonetic: "/bɪˈheɪvjər/", pos: "n.", translation: "行为，举止", level: "CET-4", example: { en: "His behavior is unacceptable.", cn: "他的行为是不可接受的。" } },
  "behind": { word: "behind", phonetic: "/bɪˈhaɪnd/", pos: "prep./adv.", translation: "在...后面", level: "CET-4", example: { en: "The garden is behind the house.", cn: "花园在房子后面。" } },
  "belief": { word: "belief", phonetic: "/bɪˈliːf/", pos: "n.", translation: "信念，相信", level: "CET-4", example: { en: "Everyone has the right to belief.", cn: "每个人都有信仰的权利。" } },
  "believe": { word: "believe", phonetic: "/bɪˈliːv/", pos: "v.", translation: "相信，认为", level: "CET-4", example: { en: "I believe in you.", cn: "我相信你。" } },
  "bell": { word: "bell", phonetic: "/bel/", pos: "n.", translation: "钟，铃", level: "CET-4", example: { en: "The bell rings at 8 o'clock.", cn: "8点钟铃响。" } },
  "belong": { word: "belong", phonetic: "/bɪˈlɔːŋ/", pos: "v.", translation: "属于", level: "CET-4", example: { en: "This book belongs to me.", cn: "这本书是我的。" } },
  "below": { word: "below", phonetic: "/bɪˈloʊ/", pos: "prep./adv.", translation: "在...下面", level: "CET-4", example: { en: "The temperature is below zero.", cn: "温度在零度以下。" } },
  "belt": { word: "belt", phonetic: "/belt/", pos: "n.", translation: "腰带，皮带", level: "CET-4", example: { en: "He wears a leather belt.", cn: "他系着一条皮带。" } },
  "bench": { word: "bench", phonetic: "/bentʃ/", pos: "n.", translation: "长凳", level: "CET-4", example: { en: "We sat on the park bench.", cn: "我们坐在公园的长凳上。" } },
  "bend": { word: "bend", phonetic: "/bend/", pos: "v./n.", translation: "弯曲，弯腰", level: "CET-4", example: { en: "Bend your knees.", cn: "弯曲你的膝盖。" } },
  "beneath": { word: "beneath", phonetic: "/bɪˈniːθ/", pos: "prep.", translation: "在...之下", level: "CET-4", example: { en: "The cat is beneath the table.", cn: "猫在桌子下面。" } },
  "benefit": { word: "benefit", phonetic: "/ˈbenɪfɪt/", pos: "n./v.", translation: "益处，好处", level: "CET-4", example: { en: "Exercise has many health benefits.", cn: "运动对健康有很多益处。" } },
  "beside": { word: "beside", phonetic: "/bɪˈsaɪd/", pos: "prep.", translation: "在...旁边", level: "CET-4", example: { en: "Sit beside me.", cn: "坐在我旁边。" } },
  "besides": { word: "besides", phonetic: "/bɪˈsaɪdz/", pos: "prep./adv.", translation: "除...之外", level: "CET-4", example: { en: "Besides English, she speaks French.", cn: "除英语外，她还会说法语。" } },
  "best": { word: "best", phonetic: "/best/", pos: "adj./adv.", translation: "最好的（地）", level: "CET-4", example: { en: "This is the best restaurant in town.", cn: "这是城里最好的餐厅。" } },
  "better": { word: "better", phonetic: "/ˈbetər/", pos: "adj./adv.", translation: "更好的（地）", level: "CET-4", example: { en: "She is getting better.", cn: "她正在好转。" } },
  "between": { word: "between", phonetic: "/bɪˈtwiːn/", pos: "prep.", translation: "在...之间", level: "CET-4", example: { en: "The shop is between the bank and the post office.", cn: "商店在银行和邮局之间。" } },
  "beyond": { word: "beyond", phonetic: "/bɪˈjɑːnd/", pos: "prep.", translation: "超过，越过", level: "CET-4", example: { en: "This is beyond my ability.", cn: "这超出了我的能力。" } },
  "bicycle": { word: "bicycle", phonetic: "/ˈbaɪsɪkl/", pos: "n.", translation: "自行车", level: "CET-4", example: { en: "I ride a bicycle to work.", cn: "我骑自行车上班。" } },
  "bike": { word: "bike", phonetic: "/baɪk/", pos: "n.", translation: "自行车，摩托车", level: "CET-4", example: { en: "My bike was stolen.", cn: "我的自行车被偷了。" } },
  "bill": { word: "bill", phonetic: "/bɪl/", pos: "n.", translation: "账单，钞票", level: "CET-4", example: { en: "Can I have the bill please?", cn: "请给我账单好吗？" } },
  "billion": { word: "billion", phonetic: "/ˈbɪljən/", pos: "n.", translation: "十亿", level: "CET-4", example: { en: "The population is over a billion.", cn: "人口超过十亿。" } },
  "bird": { word: "bird", phonetic: "/bɜːrd/", pos: "n.", translation: "鸟", level: "CET-4", example: { en: "The bird is singing.", cn: "鸟儿在歌唱。" } },
  "birth": { word: "birth", phonetic: "/bɜːrθ/", pos: "n.", translation: "出生，诞生", level: "CET-4", example: { en: "She gave birth to a baby boy.", cn: "她生了一个男婴。" } },
  "birthday": { word: "birthday", phonetic: "/ˈbɜːrθdeɪ/", pos: "n.", translation: "生日", level: "CET-4", example: { en: "Happy birthday to you!", cn: "祝你生日快乐！" } },
  "biscuit": { word: "biscuit", phonetic: "/ˈbɪskɪt/", pos: "n.", translation: "饼干", level: "CET-4", example: { en: "The baby likes biscuits.", cn: "宝宝喜欢吃饼干。" } },
  "bishop": { word: "bishop", phonetic: "/ˈbɪʃəp/", pos: "n.", translation: "主教", level: "CET-6", example: { en: "The bishop presided over the ceremony.", cn: "主教主持了仪式。" } },
  "bit": { word: "bit", phonetic: "/bɪt/", pos: "n.", translation: "一点，一些", level: "CET-4", example: { en: "Wait a bit.", cn: "等一下。" } },
  "bite": { word: "bite", phonetic: "/baɪt/", pos: "v./n.", translation: "咬", level: "CET-4", example: { en: "The dog might bite.", cn: "狗可能会咬人。" } },
  "bitter": { word: "bitter", phonetic: "/ˈbɪtər/", pos: "adj.", translation: "苦的，痛苦的", level: "CET-4", example: { en: "The medicine tastes bitter.", cn: "这药很苦。" } },
  "black": { word: "black", phonetic: "/blæk/", pos: "adj./n.", translation: "黑色的", level: "CET-4", example: { en: "She wore a black dress.", cn: "她穿了一条黑色的裙子。" } },
  "blade": { word: "blade", phonetic: "/bleɪd/", pos: "n.", translation: "刀片，刀刃", level: "CET-4", example: { en: "Be careful with the blade.", cn: "小心刀片。" } },
  "blame": { word: "blame", phonetic: "/bleɪm/", pos: "v./n.", translation: "责备，归咎于", level: "CET-4", example: { en: "Don't blame me.", cn: "别怪我。" } },
  "blank": { word: "blank", phonetic: "/blæŋk/", pos: "adj./n.", translation: "空白的；空白", level: "CET-4", example: { en: "Please fill in the blank.", cn: "请填写空白处。" } },
  "blanket": { word: "blanket", phonetic: "/ˈblæŋkɪt/", pos: "n.", translation: "毯子", level: "CET-4", example: { en: "The baby is wrapped in a blanket.", cn: "宝宝被裹在毯子里。" } },
  "blast": { word: "blast", phonetic: "/blæst/", pos: "n./v.", translation: "爆炸，冲击", level: "CET-4", example: { en: "The blast destroyed the building.", cn: "爆炸摧毁了大楼。" } },
  "blaze": { word: "blaze", phonetic: "/bleɪz/", pos: "n./v.", translation: "火焰，燃烧", level: "CET-4", example: { en: "The fire blazed all night.", cn: "大火燃烧了一整夜。" } }
};

function lookupLocalDict(word) {
  var w = word.toLowerCase().trim();
  return LOCAL_DICT[w] || null;
}

function getDictCount() {
  return Object.keys(LOCAL_DICT).length;
}